### ISSUE TITLE
AssertionError: undefined == true

### ISSUE THREAD

**Issue by nvcken** [strongloop/loopback-boot#122]
Can not start node app , occur this error

assert.js:86
  throw new assert.AssertionError({
        ^
AssertionError: undefined == true
    at /home/ken/api/node_modules/loopback/lib/model.js:392:7
    at EventEmitter.<anonymous> (/home/ken/api/node_modules/loopback/lib/model.js:222:9)
    at EventEmitter.g (events.js:199:16)
    at EventEmitter.emit (events.js:129:20)
    at EventEmitter.app.model (/home/ken/api/node_modules/loopback/lib/application.js:157:9)
    at /home/ken/api/node_modules/loopback-boot/lib/executor.js:171:9
    at Array.forEach (native)
    at setupModels (/home/ken/api/node_modules/loopback-boot/lib/executor.js:167:23)
    at execute (/home/ken/api/node_modules/loopback-boot/lib/executor.js:32:3)
    at bootLoopBackApp (/home/ken/api/node_modules/loopback-boot/index.js:129:3)

**Comment by superkhau** [comment]
Can you provide the steps to reproduce please? See https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by nvcken** [comment]
That error occurs when I run npm update for update loopback module to lastest version
Below is previous version before npm update
```
├── loopback@2.15.0
├── loopback-boot@2.6.5
├── loopback-component-storage@1.3.1
├── loopback-connector-mongodb@1.8.0
├── loopback-datasource-juggler@2.23.0
├── loopback-explorer@1.7.2

```

**Comment by superkhau** [comment]
@nvcken Is this still an issue?

**Comment by nvcken** [comment]
This is still occur, I suggest it caused by update one of Loopback -* module then newest can not work with another Loopback-* module.
I have figure out exact what confict detail yet. So I keep current set of Loopback module
