### ISSUE TITLE
Middleware param configuration broken, does not support object anymore

### ISSUE THREAD

**Issue by francois-montmasson-efg** [strongloop/loopback-boot#153]
Last release 2.12.0 introduced regression.

Here is the scenario:
* scaffold new loopback project
* just add new morgan logger in middleware with an object parameter. c.f. https://docs.strongloop.com/display/public/LB/Defining+middleware#Definingmiddleware-Middlewareconfigurationproperties
* start server

Actual Result: 
```javascript
.../node_modules/loopback-boot/lib/executor.js:330
    var match = configVariable.match(DYNAMIC_CONFIG_PARAM);
                               ^
TypeError: undefined is not a function
    at getConfigVariable (/Users/work/Desktop/loopback-boot-test/node_modules/loopback-boot/lib/executor.js:330:32)
    at Array.map (native)
    at /Users/work/Desktop/loopback-boot-test/node_modules/loopback-boot/lib/executor.js:348:41
    at Array.forEach (native)
    at interpolateVariables (/Users/work/Desktop/loopback-boot-test/node_modules/loopback-boot/lib/executor.js:345:25)
    at getUpdatedConfigObject (/Users/work/Desktop/loopback-boot-test/node_modules/loopback-boot/lib/executor.js:360:10)
    at /Users/work/Desktop/loopback-boot-test/node_modules/loopback-boot/lib/executor.js:319:19
    at Array.forEach (native)
    at setupMiddleware (/Users/work/Desktop/loopback-boot-test/node_modules/loopback-boot/lib/executor.js:310:14)
    at execute (/Users/work/Desktop/loopback-boot-test/node_modules/loopback-boot/lib/executor.js:33:3)
```

Expected Result: Start like a charm ;->

**Comment by francois-montmasson-efg** [comment]
Seems related to commit #152

**Comment by superkhau** [comment]
I can't reproduce the error. What does your `middleware.json` look like?

**Comment by francois-montmasson-efg** [comment]
```javascript
{
  "initial:before": {
    "loopback#favicon": {}
  },
  "initial": {
    "compression": {},
    "cors": {
      "params": {
        "origin": true,
        "credentials": true,
        "maxAge": 86400
      }
    },
    "morgan": {
      "params": ["dev", { "buffer": true } ]
    }
  },
  "session": {
  },
  "auth": {
  },
  "parse": {
  },
  "routes": {
  },
  "files": {
  },
  "final": {
    "loopback#urlNotFound": {}
  },
  "final:after": {
    "errorhandler": {}
  }
}
```

**Comment by superkhau** [comment]
It still works for me. Are you using the latest version of LB? `npm i -g strongloop` to update. You can clone my reproduction repo here and see if it works on your computer: https://github.com/superkhau/sandbox/tree/loopback-boot%23153

**Comment by superkhau** [comment]
Also, you can run `slc -v` to check your dependecy versions. Mine looks like:

```
strongloop v5.0.0 (node v0.10.40)
├── strong-arc@1.8.1 (15814c0)
├── strong-build@2.0.4 (9294f54)
├── strong-deploy@3.0.0 (bee617c)
├── strong-mesh-models@8.0.0 (1b220f7)
├── strong-pm@5.0.0 (dbaa1a5)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.3.1 (b17cbc0)
├─┬ strong-supervisor@3.0.2 (539c0ce)
│ └── strong-agent@1.6.4
├── generator-loopback@1.11.0 (dec0654)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3
```

**Comment by francois-montmasson-efg** [comment]
here is mine below. but it is useless since I am running directly with node.
btw, with last version of loopback-boot@2.12.1 bug fixed.
thanks for your support 
keep up the good work you do in entreprise JS with strongloop
best regards,

```javascript
$ slc -v
strongloop v5.0.0 (node v0.12.7)
├── strong-arc@1.8.1 (15814c0)
├── strong-build@2.0.4 (9294f54)
├── strong-deploy@3.0.0 (bee617c)
├── strong-mesh-models@8.0.0 (1b220f7)
├── strong-pm@5.0.0 (dbaa1a5)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.3.0 (3862a1f)
├─┬ strong-supervisor@3.0.2 (539c0ce)
│ └── strong-agent@1.6.4
├── generator-loopback@1.11.0 (dec0654)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3
```

**Comment by superkhau** [comment]
NP, glad its working for you again.
